# Generated by Django 2.1.5 on 2019-11-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_remove_salary_other_deductions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salaryMonth',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10),
        ),
    ]
