# Generated by Django 2.1.1 on 2019-10-28 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaryMonth', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=3)),
                ('salaryyear', models.IntegerField(verbose_name='Salary Year')),
                ('working_days', models.IntegerField(verbose_name='No. of working days')),
                ('working_days_worked', models.IntegerField(verbose_name='No. of days worked')),
                ('other_allowances', models.FloatField(verbose_name='Other Allowances')),
                ('other_deductions', models.FloatField(verbose_name='Other Deductions')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='CTC',
            field=models.IntegerField(default='0', verbose_name='CTC - Yearly'),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.Employee'),
        ),
    ]
