# Generated by Django 2.1.1 on 2019-11-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20191028_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
    ]
