# Generated by Django 2.1.5 on 2019-11-07 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_auto_20191106_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=10, unique=True),
        ),
    ]
