# Generated by Django 2.1.5 on 2020-04-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salaryMonth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='working_days_worked',
            field=models.IntegerField(default='0', verbose_name='No. of days worked'),
        ),
    ]
